[package]
name = "matcha_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["unstable", "client"] }
# D-Bus support via zbus
zbus = "4.0"
tokio = { version = "1.0", features = ["full"] }
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
futures = "0.3"

[build-dependencies]
wayland-scanner = "0.31"
