[package]
name = "guayusa-wl"
version = "0.2.1"
description = "A D-Bus controllable swayidle policy controller"
authors = ["Steffen Ridderbusch <steffen@robots.ox.ac.uk>"]
edition = "2024"
license = "MIT"

[dependencies]
zbus = { version = "5.7", default-features = false, features = ["tokio"] }
tokio = { version = "1.0", default-features = false, features = [
    "rt",
    "macros",
    "signal",
    "sync",
    "time",
] }
anyhow = "1.0"
log = "0.4"
env_logger = { version = "0.11", default-features = false }

# Release profile optimizations for binary size
[profile.release]
lto = "fat"
opt-level = "z"
strip = true
codegen-units = 1
overflow-checks = false

[package.metadata.generate-rpm]
assets = [
    { source = "target/x86_64-unknown-linux-gnu/release/guayusa-wl", dest = "/usr/bin/guayusa", mode = "755" },                                       # Adjust 'source' if your binary path/name is different
    { source = "systemd/guayusa.service", dest = "/usr/lib/systemd/user/guayusa.service", mode = "644" },
    { source = "systemd/guayusa-swayidle-lock.service", dest = "/usr/lib/systemd/user/guayusa-swayidle-lock.service", mode = "644" },
    { source = "systemd/guayusa-swayidle-suspend.service", dest = "/usr/lib/systemd/user/guayusa-swayidle-suspend.service", mode = "644" },
    { source = "systemd/guayusa-swayidle-before-sleep.service", dest = "/usr/lib/systemd/user/guayusa-swayidle-before-sleep.service", mode = "644" },
]

pre_uninstall_script = """
if [ $1 -eq 0 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Package removal, not upgrade
    /usr/lib/systemd/systemd-update-helper remove-user-units guayusa.service guayusa-swayidle-lock.service guayusa-swayidle-suspend.service guayusa-swayidle-before-sleep.service || :
fi
"""
post_install_script = """
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-user-units guayusa.service || :
fi
"""

[package.metadata.generate-rpm.requires]
systemd = "*"
