name: Build

on: [push, pull_request]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    container: rust:1.87

    steps:
    - name: Install GPG and RPM signing tools
      run: |
        apt-get update
        apt-get install -y gnupg rpm
      
    - name: Sigh
      run: |
        echo "Importing GPG key..."
        echo "$GPG_PUBLIC_KEY" > keyfile.asc
        
        rpm --import keyfile.asc
        rm keyfile.asc

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Cargo directories
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          target/ # Cache build target directory
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }} # Cache key
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install cargo-generate-rpm
      run: |
        CARGO_GENERATE_RPM_VERSION="0.16.1" # Specify desired version
        if ! command -v cargo-generate-rpm &> /dev/null || ! cargo-generate-rpm --version | grep -q "$CARGO_GENERATE_RPM_VERSION";
        then
            cargo install cargo-generate-rpm --version "$CARGO_GENERATE_RPM_VERSION" --locked
        else
            echo "cargo-generate-rpm version $CARGO_GENERATE_RPM_VERSION is already installed."
        fi

    - name: Build Rust binary
      run: cargo build --release --target x86_64-unknown-linux-gnu # Adjust your target as needed

    - name: Generate RPM package
      run: cargo generate-rpm

    - name: Sign RPM
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        echo "Importing GPG key..."
        echo "$GPG_PUBLIC_KEY" > RPM-GPG-KEY-pmanager
        
        rpm --import RPM-GPG-KEY-pmanager
        rm RPM-GPG-KEY-pmanager
        
        echo "Configuring .rpmmacros for signing..."
        echo "%_signature gpg" > ~/.rpmmacros
        echo "%_gpg_name Package Signing Key (RPM) >> ~/.rpmmacros
        echo "%_gpgbin $(which gpg)" >> ~/.rpmmacros

        RPM_FILE_PATH="target/generate-rpm"
        RPM_FILE=$(find "$RPM_FILE_PATH" -name "*.rpm" -print -quit)

        echo "Found RPM: $RPM_FILE, attempting to sign..."
        echo "${GPG_PASSPHRASE}" | rpmsign --addsign "$RPM_FILE"

        echo "Verifying"
        rpm --checksig "$RPM_FILE"
